
log_dir: "logs/"
#DS_path: 'C:\Users\fsalm\Desktop\DynEO4SLUMS\nairobi\planetscope\nairobi_psb_sd_20230129_surfrefl_8bands_psscene_analytic_8b_sr_udm2\slices'
#DS_path: 'C:\Users\fsalm\Desktop\DynEO4SLUMS\nairobi\planetscope\nairobi_psb_sd_20230129_surfrefl_8bands_psscene_analytic_8b_sr_udm2\ds'
DS_path: '/home/feras/Desktop/DynEO4SLUMS/nairobi_psb_sd_20230129_surfrefl_8bands_psscene_analytic_8b_sr_udm2/ds'

im_size: 128

use_gpu: true
gpuID: 0
nThreads: 1
scale: 2

dparallel: true
epochs: 1000
batchSize: 12
load: false

lr: 0.001
weight_decay: 0.0005
lrdecay_iter: 2000
lrdecay_gamma: 0.5
beta1: 0.9

lossType: "MSE"
save_freq: 1
valid_freq: 1

in_channels: 3
valchannel: 3


